name = "EmacsVterm"
uuid = "b2ad6718-fff2-47f2-82f8-4d98a2866c7e"
authors = ["Michal Sojka <michal.sojka@cvut.cz> and contributors"]
version = "0.2.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
